import { ArrowRight, BadgeCheck, Layers, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import SEOHead from "@/components/SEOHead";
import SectionReveal from "@/components/SectionReveal";

const benefits = [
  { icon: Layers, title: "Inventory access", text: "Approved brokers can request access to A1 Tradelines inventory and matching resources." },
  { icon: BadgeCheck, title: "Partner pricing", text: "Eligible tradelines may qualify for up to 25% off, subject to approval and program terms." },
  { icon: ShieldCheck, title: "Agency-ready support", text: "White-label resources and practical operational guidance for qualified partners." },
];

export default function BrokerProgram() {
  return <div className="pt-20">
    <SEOHead title="A1 Tradelines Broker Program | Partner Resources" description="Apply for the A1 Tradelines Broker Program for approved inventory access, white-label resources, and eligible partner pricing." canonical="https://a1tradelines.com/broker-program" />
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#f8f8f6] px-4 py-20 sm:px-6 lg:px-8"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-blue-700 via-sky-400 to-lime-300"/><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><SectionReveal><p className="text-xs font-black tracking-[.18em] text-blue-700">A1 PARTNER PROGRAM</p><h1 className="mt-5 max-w-3xl text-left text-5xl font-black tracking-[-.045em] text-[#101b33] sm:text-6xl">A more polished way to serve your clients.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">The A1 Tradelines Broker Program gives approved partners a clear path to curated authorized-user tradeline options, education, and agency resources.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#111d37] px-6 py-4 font-bold text-white transition-transform duration-150 hover:-translate-y-0.5 hover:bg-blue-700">Apply to Partner <ArrowRight size={18}/></Link><a href="https://www.gohighlevel.com/?fp_ref=geekinai67" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-6 py-4 font-bold text-[#101b33] hover:border-blue-400">Get GoHighLevel for Your Agency <ArrowRight size={18}/></a></div></SectionReveal><SectionReveal delay={.12}><div className="rounded-3xl border border-white bg-white/70 p-8 shadow-[0_24px_70px_rgba(20,44,84,.12)] backdrop-blur"><p className="text-xs font-black tracking-[.16em] text-slate-500">PARTNER STANDARDS</p><p className="mt-5 text-2xl font-bold leading-8 text-[#101b33]">Built for approved brokers who value a measured, client-first approach.</p><div className="mt-8 border-t border-slate-200 pt-6 text-sm leading-6 text-slate-600">No fake portals, no outcome guarantees, and no request for Social Security numbers or account credentials through a general partner form.</div></div></SectionReveal></div></section>
    <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-black tracking-[.18em] text-blue-700">WHAT APPROVED PARTNERS RECEIVE</p><h2 className="mt-4 text-left text-4xl font-black tracking-[-.04em] text-[#101b33]">Designed for practical growth.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{benefits.map(({icon: Icon,title,text}) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><Icon className="text-blue-700"/><h3 className="mt-6 text-left text-xl font-bold text-[#101b33]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section>
  </div>;
}
