import { useMemo, useState } from "react";
import SEOHead from "@/components/SEOHead";

export default function TradelineCalculator() {
  const [limit, setLimit] = useState(0);
  const [balance, setBalance] = useState(0);
  const utilization = useMemo(() => limit > 0 ? Math.round((balance / limit) * 100) : 0, [limit, balance]);
  return <div className="bg-[#f4f5f7] px-5 pb-20 pt-32 sm:px-8 lg:px-12"><SEOHead title="Credit Utilization Calculator | A1 Tradelines" description="Use A1 Tradelines' simple calculator to estimate credit utilization from your total limits and balances. Educational use only." canonical="https://a1tradelines.com/tradeline-calculator"/><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">FREE CREDIT TOOL</p><h1 className="mt-5 text-left text-5xl font-black tracking-[-.05em] text-[#12213f] sm:text-7xl">Credit utilization calculator.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-700">Enter your total card limits and balances to estimate utilization. This is an educational estimate, not a score prediction.</p><div className="mt-10 grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 sm:p-8"><label className="text-sm font-bold text-[#12213f]">Total credit limits<input type="number" min="0" value={limit || ""} onChange={e => setLimit(Number(e.target.value))} className="mt-2 w-full border border-slate-300 px-4 py-3 text-[#12213f]" placeholder="0"/></label><label className="text-sm font-bold text-[#12213f]">Total balances<input type="number" min="0" value={balance || ""} onChange={e => setBalance(Number(e.target.value))} className="mt-2 w-full border border-slate-300 px-4 py-3 text-[#12213f]" placeholder="0"/></label><div className="sm:col-span-2 rounded-xl bg-[#12213f] p-6 text-white"><p className="text-sm text-white/70">Estimated utilization</p><p className="mt-2 text-5xl font-black text-lime-300">{utilization}%</p><p className="mt-3 text-sm text-white/70">Credit models and lenders may evaluate profiles differently.</p></div></div></div></div>;
}
