export const site = {
  name: 'A1 Tradelines',
  legalName: 'A1 Tradelines',
  domain: 'https://www.a1tradelines.com',
  url: 'https://www.a1tradelines.com',
  description:
    'A1 Tradelines is a transparent marketplace to buy seasoned authorized-user tradelines. Compare account age, credit limit, utilization, and bureau reporting, then buy with a 100% money-back guarantee if it does not post.',
  phone: '908-767-5309',
  phoneHref: 'tel:9087675309',
  email: 'info@a1tradelines.com',
  emailHref: 'mailto:info@a1tradelines.com',
  city: 'Newark',
  state: 'NJ',
  guarantee: 'If your tradeline does not post, you get 100% of your money back.',
  bookingToken: 'eXgzNXRrM1gyVXN3ZTBkMWo0U2xidz09',
  bookingUrl: 'https://app.tradelinescore.com/authorized-user-tradeline/eXgzNXRrM1gyVXN3ZTBkMWo0U2xidz09',
  keywords: [
    'buy tradelines',
    'authorized user tradelines',
    'aged tradelines',
    'seasoned tradelines',
    '3 bureau tradelines',
    'tradelines for sale',
    'tradeline pricing',
    'tradelines for mortgage',
    'tradelines for auto loan',
    'how tradelines work',
  ],
}

